### ISSUE TITLE
.net framework

### ISSUE THREAD

**Issue by zhuwei3359** [mkjeff/secs4net#10] opened 2017-06-01 06:44 UTC
can i change the 4.6.2 microsoft.net framework to 4.5.2 ? is there any problem?

**Comment by zhuwei3359** [comment] 2017-06-01 07:53
@mkjeff

**Comment by mkjeff** [comment] 2017-06-01 12:54
the current version uses Array.Empty<T> method. it only available on 4.6+
It is not difficult to get rid of the dependency and downgrade to 4.5.2.

**Comment by zhuwei3359** [comment] 2017-06-02 01:24
so you mean it's totally ok to downgrade to 4.5.2.？ @mkjeff

**Comment by zhuwei3359** [comment] 2017-06-02 01:26
i set up the 4.6.2 version on my pc， but the software visual studio2015 can  not recognize it. @mkjeff

**Comment by mkjeff** [comment] 2017-06-02 02:10
@zhuwei3359 you have to install the corresponding version of [Developer Pack](https://www.microsoft.com/net/targeting).

**Comment by zhuwei3359** [comment] 2017-06-02 02:22
@mkjeff  i'll try ，thanks a lot

**Comment by zhuwei3359** [comment] 2017-06-02 02:34
@mkjeff   thanks for your advice， the  4.6.2 version is available now.  bravo

**Comment by zhuwei3359** [comment] 2017-06-02 05:33
@mkjeff  i think there is some faults in item.cs.  The brackets are not matching .can i get some advice？

**Comment by zhuwei3359** [comment] 2017-06-02 07:47
@mkjeff   sorry, i download the older version resource code. i just found that, now it's totally ok!

**Comment by zhuwei3359** [comment] 2017-06-07 03:12
@mkjeff i have some question about the header.DeviceId ，is the default value 12320？ i set the device number 16， and got a  frame of data from the window 00 00 00 0A FF FF 00 00 00 01 1A FB 81 75（select.req），and i reply 00 00 00 0A 00 10 00 00 00 02 1A FB 81 75（select.rsp），and then the window tell me：Received Unrecognized Device Id Message， and  i find that the value of the header.DeviceId is 12320

**Comment by mkjeff** [comment] 2017-06-07 06:53
Default device id is 0(ushort), please make sure the device id of both client/server are the same.

00 00 00 0A **FF FF** 00 00 00 01 1A FB 81 75
00 00 00 0A **00 10** 00 00 00 02 1A FB 81 75

**Comment by zhuwei3359** [comment] 2017-06-07 06:58
so  the correct transaction is：
00 00 00 0A FF FF 00 00 00 01 1A FB 81 75
00 00 00 0A FF FF 00 00 00 02 1A FB 81 75
is this right？ @mkjeff

**Comment by zhuwei3359** [comment] 2017-06-08 01:53
@mkjeff   i got another question. this project should be regarded as an equipment or a host？

**Comment by mkjeff** [comment] 2017-06-08 04:07
The API design has no assumption on this. it should be work on both sides.

**Comment by zhuwei3359** [comment] 2017-06-12 11:09
@mkjeff  sorry for bothering you again. if i want to reply a primary message，what is the format that i should input to the interface window？   for example s1f2.

**Comment by Joan2019** [comment] 2019-01-21 08:10
Can you help me? I get this error message,OS:Win10 ,visual studio community 2017 version:15.9.5
System.IO.FileNotFoundException: 未能加载文件或程序集“System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”或它的某一个依赖项。系统找不到指定的文件。
文件名:“System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”
   在 Secs4Net.StreamDecoder.<.ctor>g__GetMessageHeader|23_1(Int32& length, Int32& need)
   在 Secs4Net.StreamDecoder.<.ctor>g__GetTotalMessageLength|23_0(Int32& length, Int32& need)
   在 Secs4Net.StreamDecoder.Decode(Int32 length)
   在 Secs4Net.SecsGem.<.ctor>g__SocketReceiveEventCompleted|84_9(Object sender, SocketAsyncEventArgs e)

**Comment by keinen-lab** [comment] 2019-02-27 02:37
@Joan2019  Do you have resolved this problem?  I have same problem. 
if you resolved this problem, I want to know answer.

**Comment by dzhydaniel** [comment] 2019-07-17 00:42
@zhuwei3359 do you have any progress of this project ?

**Comment by zhuwei3359** [comment] 2019-07-17 02:03
no, i leave the company who wants to do this project  one year ago.


------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午8:42
收件人: "mkjeff/secs4net"<secs4net@noreply.github.com>;
抄送: "晴空"<498552020@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [mkjeff/secs4net] .net framework (#10)




@zhuwei3359 do you have any progress of this project ?

**Comment by dzhydaniel** [comment] 2019-07-17 05:39
@keinen-lab @Joan2019 do you have any progress on this project?

**Comment by nevernet** [comment] 2019-12-20 10:57
@Joan2019 @dzhydaniel @keinen-lab i also got System.memory cannot be loaded issue,  cause there is no version=4.0.1.1.

i found that under vs2017, the system.memory has been upgraded to 4.5.3 automatically by vs2017. 
the problem is why code is still raise the error. 

any ideas will be appreciated.
thank you

**Comment by mkjeff** [comment] 2021-07-23 12:39
.net framework was outdated on v2 roadmap. so, close the issue

**Closed by mkjeff** 2021-07-23 12:39 UTC
